apiVersion: batch/v1
kind: Job
metadata:
  name: sealos-job
  labels:
    app: sealos-job
spec:
  backoffLimit: 1
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      volumes:
        - emptyDir: { }
          name: sealos
        - emptyDir: { }
          name: containers
        - name: tmp
          emptyDir: { }
      initContainers:
        - name: copy
          image: ghcr.io/labring/sealos:v4.1.3
          command: [ "/bin/sh", "-c", "cp /usr/bin/sealos /data/" ]
          volumeMounts:
            - name: tmp
              mountPath: /data
      containers:
        - name: sealos
          image: ubuntu:18.04
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - "bash"
            - "-c"
            - |
              apt-get -qq update 
              apt-get -qq install -y --no-install-recommends ca-certificates curl
              chmod a+x /data/sealos
          volumeMounts:
            - name: sealos
              mountPath: /var/lib/sealos
            - name: containers
              mountPath: /var/lib/containers
            - name: tmp
              mountPath: /data
---

